# permissions for end users to view cores.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: core-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: af-operator
    app.kubernetes.io/part-of: af-operator
    app.kubernetes.io/managed-by: kustomize
  name: core-viewer-role
rules:
- apiGroups:
  - node.cardano.io
  resources:
  - cores
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - node.cardano.io
  resources:
  - cores/status
  verbs:
  - get
