# permissions for end users to view relays.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: relay-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: cardano-operator
    app.kubernetes.io/part-of: cardano-operator
    app.kubernetes.io/managed-by: kustomize
  name: relay-viewer-role
rules:
- apiGroups:
  - node.cardano.io
  resources:
  - relays
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - node.cardano.io
  resources:
  - relays/status
  verbs:
  - get
