apiVersion: node.apexfusion.com/v1alpha1
kind: Relay
metadata:
  labels:
    app.kubernetes.io/name: relay
    app.kubernetes.io/instance: relay-sample
    app.kubernetes.io/part-of: af-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: af-operator
  name: relay-sample
spec:
  # TODO(user): Add fields here
