apiVersion: node.cardano.io/v1alpha1
kind: Relay
metadata:
  labels:
    app.kubernetes.io/name: relay
    app.kubernetes.io/instance: relay-sample
    app.kubernetes.io/part-of: cardano-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: cardano-operator
  name: cardano-relay
spec:
  replicas: 1
  protocol: apexfusion
  network: testnet
  image: "ghcr.io/intersectmbo/cardano-node:8.7.3"
  resources:
    requests:
      cpu: 1
      memory: 2Gi
    limits:
      cpu: 2
      memory: 4Gi
  storage:
    accessModes:
      - "ReadWriteOnce"
    storageClassName: "hostpath"
    resources:
      requests:
        storage: 5Gi
  service:
    type: ClusterIP
    port: 31400
  configuration: 
    name: 'relay-config'
  genesis:
    name: 'genesis'

---
apiVersion: v1
kind: ConfigMap
metadata:
  name:  'relay-config'
data:
  configuration.yaml: |
    ByronGenesisFile: /configuration/byron_genesis.json
    ShelleyGenesisFile: /configuration/shelley_genesis.json
    AlonzoGenesisFile: /configuration/alonzo_genesis.json
    ConwayGenesisFile: /configuration/conway_genesis.json
    SocketPath: db/node.socket
    PBftSignatureThreshold: 0.6
    MaxConcurrencyBulkSync: 1
    MaxConcurrencyDeadline: 2
    Protocol: Cardano
    PBftSignatureThreshold: 0.6
    RequiresNetworkMagic: RequiresMagic
    LastKnownBlockVersion-Major: 6
    LastKnownBlockVersion-Minor: 0
    LastKnownBlockVersion-Alt: 0
    TurnOnLogging: True
    TurnOnLogMetrics: True
    minSeverity: Debug
    TracingVerbosity: NormalVerbosity
    setupBackends:
      - KatipBK
    defaultBackends:
      - KatipBK
    hasEKG: 12788
    hasPrometheus:
      - "0.0.0.0"
      - 8080
    setupScribes:
      - scKind: StdoutSK
        scName: stdout
        scFormat: ScText
    defaultScribes:
      - - StdoutSK
        - stdout
    rotation:
      rpLogLimitBytes: 5000000
      rpKeepFilesNum:  3
      rpMaxAgeHours:   24
    TraceBlockFetchClient: False
    TraceBlockFetchDecisions: False
    TraceBlockFetchProtocol: False
    PBftSignatureThreshold: 0.6
    TraceBlockFetchProtocolSerialised: False
    PBftSignatureThreshold: 0.6
    TraceBlockFetchServer: False
    TraceBlockchainTime: False
    TraceChainDb: True
    TraceChainSyncClient: False
    TraceChainSyncBlockServer: False
    TraceChainSyncHeaderServer: False
    TraceChainSyncProtocol: False
    PBftSignatureThreshold: 0.6
    TraceDNSResolver: True
    TraceDNSSubscription: True
    TraceErrorPolicy: True
    TraceLocalErrorPolicy: True
    TraceForge: True
    TraceHandshake: False
    TraceIpSubscription: True
    TraceLocalRootPeers: True
    TracePublicRootPeers: True
    TracePeerSelection: True
    TraceDebugPeerSelection: False
    TracePeerSelectionActions: True
    TraceConnectionManager: True
    TraceServer: True
    TraceLocalConnectionManager: False
    TraceLocalServer: False
    TraceLocalChainSyncProtocol: False
    PBftSignatureThreshold: 0.6
    TraceLocalHandshake: False
    TraceLocalTxSubmissionProtocol: False
    PBftSignatureThreshold: 0.6
    TraceLocalTxSubmissionServer: False
    TraceMempool: True
    TraceMux: False
    TraceTxInbound: False
    TraceTxOutbound: False
    TraceTxSubmissionProtocol: False
    PBftSignatureThreshold: 0.6
    options:
      mapBackends:
        cardano.node.metrics:
          - EKGViewBK
      mapScribes:
        cardano.node.metrics:
          - "FileSK::logs/mainnet.log"
      mapSeverity:
        cardano.node.ChainDB: Notice
        cardano.node.DnsSubscription: Debug
    TestShelleyHardForkAtEpoch: 0
    TestAllegraHardForkAtEpoch: 0
    TestMaryHardForkAtEpoch: 0
    TestAlonzoHardForkAtEpoch: 0
    TestBabbageHardForkAtEpoch: 0
    ExperimentalProtocolsEnabled: True
    ByronGenesisHash: acd3e7c4cc071ae176fa253e654f0dd4e759892b16e958d8bd3c393f5c6c66d2
    ShelleyGenesisHash: 0b67b0cb16e973478888efb1c7f69fca8e80489369afed94624a588e94a94f2b
    AlonzoGenesisHash: 0f715ff78fcab739c6cb2cc1073eb87d0ffe3514218bfa0337d416f6fbaf7886
    ConwayGenesisHash: 42d43350244fb70d5f07a13778c549c916d006f8dfc1f540f605bb3084443147
    EnableP2P: True
    TargetNumberOfRootPeers: 20
    TargetNumberOfKnownPeers: 20
    TargetNumberOfEstablishedPeers: 10
    TargetNumberOfActivePeers: 10
    TraceInboundGovernorCounters: True
    TraceConnectionManagerTransitions: True
    TraceLedgerPeers: True
    TracePeerSelectionCounters: True
    TracePeerStateActions: True

---
apiVersion: v1
kind: ConfigMap
metadata:
  name:  'genesis'
data:
  byron_genesis.json: |
    {
      "bootStakeholders": {
        "06c001b8bf889a1ad73588353e64d737874eaadfb9e9dd2d689de8c4": 1,
        "304967a59c491d7ed837dd0a32b7acb21fdf4c8f0bd6ec0c8eee744a": 1
    },
    "heavyDelegation": {
      "06c001b8bf889a1ad73588353e64d737874eaadfb9e9dd2d689de8c4": {
        "omega": 0,
        "issuerPk": "vhKuT7EUuIS0YXHP+vcbf0lgRXnI+pTCwOAoQHYlEwxuSNP/OpBQuS6YFje78FR4bor+GDdNWDIE/iBQ/hEuww==",
        "delegatePk": "lNyzvukBzTOBj6KZK/izQWNcUNFn+mLBHveotfG652z2pBrF7Wf3t0saV1y85/L0tIZGYLcqxNb59FES0jex6A==",
        "cert": "097ec03013c4289bb2dadaad5e5b2ac646047d46e590ade12faa7eda22622d21cf562cd74286a9b12ca97e6c1929ad3ff579b80a8ca79dfaa64a9cb19adc3503"
      },
      "304967a59c491d7ed837dd0a32b7acb21fdf4c8f0bd6ec0c8eee744a": {
        "omega": 0,
        "issuerPk": "p7r7BAkUQ9nhpqzxa97LBbuc9q1AaMn2Bg/wR8GP39Ky3tdWuososkzhTU8eKLUn8E52P14a3RwIMjANG2KpJg==",
        "delegatePk": "3wpiHBAgniDyjtvxXVSuo6YjYqPlV2bewwZP7Mm+5d721e6L1VCwBbiLkqhBr07aQzwcAFCq4kH0Sqv8C2/qYA==",
        "cert": "6ae540d57e4bb53c9935131f3f8f3b7fd5e78f5f851844913f5f13dd60bd4e33333c372aff538dfe0a399ecf945d399435e270dcd03d1dc63bc6435c59c7dc09"
      }
    },
    "startTime": 1715879890,
    "nonAvvmBalances": {
      "5oP9ib6ym3XcVeLuFARfLXk29LA15hAPfydXkde5srks6VtdKDVLtEpcVw924KsBhp": "1200000000000000",
      "5oP9ib6ym3XjQWwQs7Uf2jdMouJ3zTTsCjY3e6wpPuxuznGVfkPFPM1RycKbb1cF9Q": "1200000000000000"
    },
    "blockVersionData": {
      "scriptVersion": 0,
      "slotDuration": "20000",
      "maxBlockSize": "2000000",
      "maxHeaderSize": "2000000",
      "maxTxSize": "4096",
      "maxProposalSize": "700",
      "mpcThd": "20000000000000",
      "heavyDelThd": "300000000000",
      "updateVoteThd": "1000000000000",
      "updateProposalThd": "100000000000000",
      "updateImplicit": "10000",
      "softforkRule": {
        "initThd": "900000000000000",
        "minThd": "600000000000000",
        "thdDecrement": "50000000000000"
      },
      "txFeePolicy": {
        "summand": "155381000000000",
        "multiplier": "43946000000"
      },
      "unlockStakeEpoch": "18446744073709551615"
    },
    "protocolConsts": {
      "k": 2160,
      "protocolMagic": 3311
    },
    "avvmDistr": {}
    }

  shelley_genesis.json: |
    {
      "systemStart": "2024-05-16T17:18:10.000000000Z",
      "networkMagic": 3311,
      "networkId": "Testnet",
      "activeSlotsCoeff": 0.05,
      "securityParam": 2160,
      "epochLength": 432000,
      "slotsPerKESPeriod": 129600,
      "maxKESEvolutions": 62,
      "slotLength": 1,
      "updateQuorum": 2,
      "maxLovelaceSupply": 3000000000000000,
      "protocolParams": {
        "minFeeA": 47,
        "minFeeB": 158298,
        "maxBlockBodySize": 65536,
        "maxTxSize": 16384,
        "maxBlockHeaderSize": 1100,
        "keyDeposit": 0,
        "poolDeposit": 0,
        "eMax": 18,
        "nOpt": 100,
        "a0": 0.0,
        "rho": 0.0038,
        "tau": 0.000001,
        "minPoolCost": 0,
        "decentralisationParam": 0.7,
        "extraEntropy": {
          "tag": "NeutralNonce"
        },
        "protocolVersion": {
          "major": 7,
          "minor": 0
        },
        "minUTxOValue": 1000000
      },
      "genDelegs": {
        "77f435dd4e769a31ace8d23078542b79578d767f9a14fd9858abf9db": {
          "delegate": "63762a935ead263b8435d51f9df0dcaf9ccdfafc8a9bfd64cb533ac9",
          "vrf": "c5c467bd6edd9d21f5e38d3ac5cdd7524fb58745a965a342d96838827271bb97"
        },
        "b5b9cfe727de1e5477f6a3cbc5a648f1e5905972bcb555d64bc9fc8e": {
          "delegate": "6bc3de0c94fb57ea31a6d8b1dbee6a8ce3c584a7a54cf36b113944cd",
          "vrf": "554a4acd2d59b638e523cd1813c43e2258685dc343ddadb040504e771e332c33"
        }
      },
      "initialFunds": {
        "60b74de7a8eddb1e47eeb0bab3a8c7df59a0100f03efb5bcae1eb95e2a": 900000,
        "607e100b21dfd524c03a8e32afd48b3e38a1ba2bbb99459c4c1c41e8bc": 900000,
        "00b51d28881ec562a2c6d63a78efb32dfa1715456943319fbb78dfe32ddb136ac0a99040ebe275b83c232f266d690d57a7ee04c1fdd04f3efc": 900000,
        "00183558e691a4e63669138b927f6c90262f07a15dee2278ce86b5898f452d2897f85548e0d6b601544260119b9b8accf5867efe36e336feb0": 900000
      },
      "staking": {
        "pools": {
          "d83c01cbdd3468741cb9bb7366a7d2088d20307d07dd6332fc8e0415": {
            "cost": 0,
            "margin": 0.0,
            "metadata": null,
            "owners": [],
            "pledge": 0,
            "publicKey": "d83c01cbdd3468741cb9bb7366a7d2088d20307d07dd6332fc8e0415",
            "relays": [],
            "rewardAccount": {
              "credential": {
                "keyHash": "97a39de41160b64d3b86edbbff925bfe123ca6caf922d2119774d272"
              },
              "network": "Testnet"
            },
            "vrf": "641fce1d850f2316b9ab49b84de531af7f27f7a21d16644398fa4e224421e9db"
          },
          "a6500f8ee0c887495aaa339d7fc9820e098385b0dd608bbf8452917f": {
            "cost": 0,
            "margin": 0.0,
            "metadata": null,
            "owners": [],
            "pledge": 0,
            "publicKey": "a6500f8ee0c887495aaa339d7fc9820e098385b0dd608bbf8452917f",
            "relays": [],
            "rewardAccount": {
              "credential": {
                "keyHash": "f0a2b82b9835c9e57915263b595b541778d35c110147f9219a78582c"
              },
              "network": "Testnet"
            },
            "vrf": "93911f5027ba74e2c926bee4c0a1e922375f60b365e8e4f9089abb0b4a1f70d1"
          }
        },
        "stake": {
          "db136ac0a99040ebe275b83c232f266d690d57a7ee04c1fdd04f3efc": "d83c01cbdd3468741cb9bb7366a7d2088d20307d07dd6332fc8e0415",
          "452d2897f85548e0d6b601544260119b9b8accf5867efe36e336feb0": "a6500f8ee0c887495aaa339d7fc9820e098385b0dd608bbf8452917f"
        }
      }
    }

  alonzo_genesis.json: |
    {
      "collateralPercentage": 150,
      "costModels": {
        "PlutusV1": [
          197209,
          0,
          1,
          1,
          396231,
          621,
          0,
          1,
          150000,
          1000,
          0,
          1,
          150000,
          32,
          2477736,
          29175,
          4,
          29773,
          100,
          29773,
          100,
          29773,
          100,
          29773,
          100,
          29773,
          100,
          29773,
          100,
          100,
          100,
          29773,
          100,
          150000,
          32,
          150000,
          32,
          150000,
          32,
          150000,
          1000,
          0,
          1,
          150000,
          32,
          150000,
          1000,
          0,
          8,
          148000,
          425507,
          118,
          0,
          1,
          1,
          150000,
          1000,
          0,
          8,
          150000,
          112536,
          247,
          1,
          150000,
          10000,
          1,
          136542,
          1326,
          1,
          1000,
          150000,
          1000,
          1,
          150000,
          32,
          150000,
          32,
          150000,
          32,
          1,
          1,
          150000,
          1,
          150000,
          4,
          103599,
          248,
          1,
          103599,
          248,
          1,
          145276,
          1366,
          1,
          179690,
          497,
          1,
          150000,
          32,
          150000,
          32,
          150000,
          32,
          150000,
          32,
          150000,
          32,
          150000,
          32,
          148000,
          425507,
          118,
          0,
          1,
          1,
          61516,
          11218,
          0,
          1,
          150000,
          32,
          148000,
          425507,
          118,
          0,
          1,
          1,
          148000,
          425507,
          118,
          0,
          1,
          1,
          2477736,
          29175,
          4,
          0,
          82363,
          4,
          150000,
          5000,
          0,
          1,
          150000,
          32,
          197209,
          0,
          1,
          1,
          150000,
          32,
          150000,
          32,
          150000,
          32,
          150000,
          32,
          150000,
          32,
          150000,
          32,
          150000,
          32,
          3345831,
          1,
          1
        ],
        "PlutusV2": [
          205665,
          812,
          1,
          1,
          1000,
          571,
          0,
          1,
          1000,
          24177,
          4,
          1,
          1000,
          32,
          117366,
          10475,
          4,
          23000,
          100,
          23000,
          100,
          23000,
          100,
          23000,
          100,
          23000,
          100,
          23000,
          100,
          100,
          100,
          23000,
          100,
          19537,
          32,
          175354,
          32,
          46417,
          4,
          221973,
          511,
          0,
          1,
          89141,
          32,
          497525,
          14068,
          4,
          2,
          196500,
          453240,
          220,
          0,
          1,
          1,
          1000,
          28662,
          4,
          2,
          245000,
          216773,
          62,
          1,
          1060367,
          12586,
          1,
          208512,
          421,
          1,
          187000,
          1000,
          52998,
          1,
          80436,
          32,
          43249,
          32,
          1000,
          32,
          80556,
          1,
          57667,
          4,
          1000,
          10,
          197145,
          156,
          1,
          197145,
          156,
          1,
          204924,
          473,
          1,
          208896,
          511,
          1,
          52467,
          32,
          64832,
          32,
          65493,
          32,
          22558,
          32,
          16563,
          32,
          76511,
          32,
          196500,
          453240,
          220,
          0,
          1,
          1,
          69522,
          11687,
          0,
          1,
          60091,
          32,
          196500,
          453240,
          220,
          0,
          1,
          1,
          196500,
          453240,
          220,
          0,
          1,
          1,
          1159724,
          392670,
          0,
          2,
          806990,
          30482,
          4,
          1927926,
          82523,
          4,
          265318,
          0,
          4,
          0,
          85931,
          32,
          205665,
          812,
          1,
          1,
          41182,
          32,
          212342,
          32,
          31220,
          32,
          32696,
          32,
          43357,
          32,
          32247,
          32,
          38314,
          32,
          35892428,
          10,
          9462713,
          1021,
          10,
          38887044,
          32947,
          10
        ]
      },
      "executionPrices": {
        "prMem": 5.77,
        "prSteps": 0.00721
      },
      "lovelacePerUTxOWord": 34482,
      "maxBlockExUnits": {
        "exUnitsMem": 80000000,
        "exUnitsSteps": 40000000000
      },
      "maxCollateralInputs": 3,
      "maxTxExUnits": {
        "exUnitsMem": 16000000,
        "exUnitsSteps": 10000000000
      },
      "maxValueSize": 5000
    }

  conway_genesis.json: |
    {
        "committee": {
            "members": {},
            "quorum": 0.0
        },
        "committeeMaxTermLength": 200,
        "committeeMinSize": 0,
        "constitution": {
            "anchor": {
                "dataHash": "0000000000000000000000000000000000000000000000000000000000000000",
                "url": ""
            }
        },
        "dRepActivity": 20,
        "dRepDeposit": 2000000,
        "dRepVotingThresholds": {
            "dvtCommitteeNoConfidence": 0.51,
            "dvtCommitteeNormal": 0.51,
            "dvtHardForkInitiation": 0.51,
            "dvtMotionNoConfidence": 0.51,
            "dvtPPEconomicGroup": 0.51,
            "dvtPPGovGroup": 0.51,
            "dvtPPNetworkGroup": 0.51,
            "dvtPPTechnicalGroup": 0.51,
            "dvtTreasuryWithdrawal": 0.51,
            "dvtUpdateToConstitution": 0.51
        },
        "govActionDeposit": 1000000000,
        "govActionLifetime": 10,
        "poolVotingThresholds": {
            "pvtCommitteeNoConfidence": 0.51,
            "pvtCommitteeNormal": 0.51,
            "pvtHardForkInitiation": 0.51,
            "pvtMotionNoConfidence": 0.51
        }
    }

