name: CD

on:
  pull_request:
    branches: [ "main" ]
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

jobs:
  deploy:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Deploy
      run: |
        set -e
        echo "test deploy"