name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  format:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Format
      run: |
        set -e
        make fmt

  vet:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Vet
      run: |
        set -e
        make vet

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Test
      run: |
        set -e
        make test
    
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Lint
      run: |
        set -e
        make lint

  


